# Generated by Django 5.1.5 on 2025-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_habitacion_alter_cliente_direccion_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
