# Generated by Django 5.1.5 on 2026-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_rename_telefone_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_ingreso']},
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_salida__gt', models.F('fecha_ingreso'))), name='reserva_fecha_salida_posterior_a_ingreso'),
        ),
    ]
