# Generated by Django 5.1.5 on 2026-08-27 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_habitacion_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveSmallIntegerField(default=1, help_text='Huéspedes máximos')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camas', models.PositiveSmallIntegerField(default=1)),
                ('servicios_incluidos', models.TextField(blank=True, help_text='Lista libre por ahora (ej: "wifi, desayuno"); se formaliza en el módulo de Servicios.')),
            ],
            options={
                'ordering': ['precio_base'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('Cedula', 'Cédula'), ('Pasaporte', 'Pasaporte'), ('RUC', 'RUC'), ('Otro', 'Otro')], default='Cedula', max_length=20),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Ej: vista al mar, balcón, aire acondicionado (texto libre por ahora).', null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='N.º de documento'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Ocupada', 'Ocupada'), ('Limpieza', 'Limpieza'), ('Mantenimiento', 'Mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio de esta habitación en particular; si se deja en blanco se usa el del tipo.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='reservas.tipohabitacion'),
        ),
    ]
