# Generated by Django 5.1.5 on 2026-08-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_seed_tipos_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='check_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
