# Generated by Django 5.1.5 on 2026-08-27 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_check_in_at_reserva_check_out_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('categoria', models.CharField(choices=[('Restaurante', 'Restaurante'), ('Minibar', 'Minibar'), ('Lavanderia', 'Lavandería'), ('Parqueadero', 'Parqueadero'), ('Transporte', 'Transporte'), ('Room service', 'Room service'), ('Otros', 'Otros')], default='Otros', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no aparece para agregar consumos nuevos.')),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='reservas.reserva')),
                ('usuario', models.ForeignKey(blank=True, help_text='Quién lo registró.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.servicio')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
