# Generated by Django 5.1.5 on 2026-08-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_tarealimpieza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=10)),
                ('estado', models.CharField(choices=[('Reportado', 'Reportado'), ('En revisión', 'En revisión'), ('En reparación', 'En reparación'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Reportado', max_length=20)),
                ('solucion', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='reservas.habitacion')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'incidencias',
                'ordering': ['-creada_en'],
            },
        ),
    ]
