# Generated by Django 5.1.5 on 2026-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
    ]
