# Generated by Django 5.1.5 on 2026-08-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_reserva_creada_en_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, help_text='Obligatorio para Transferencia y Tarjeta.', max_length=100, verbose_name='N.º de comprobante / referencia'),
        ),
    ]
