# Generated by Django 5.1.5 on 2026-08-27 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_pago_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(default='Sistema Hotelero', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ruc', models.CharField(blank=True, max_length=20, verbose_name='RUC / NIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda (código)')),
                ('hora_checkin_default', models.TimeField(default=datetime.time(14, 0))),
                ('hora_checkout_default', models.TimeField(default=datetime.time(12, 0))),
                ('politica_cancelacion', models.TextField(blank=True, help_text='Texto informativo — todavía no bloquea cancelaciones automáticamente.')),
            ],
            options={
                'verbose_name': 'configuración del hotel',
                'verbose_name_plural': 'configuración del hotel',
            },
        ),
    ]
