# Generated by Django 5.1.5 on 2026-08-27 20:41

import reservas.validadores_ecuador
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_configuracionhotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(help_text='Cédula (10 dígitos) o RUC (13 dígitos) según el tipo elegido abajo.', max_length=13, primary_key=True, serialize=False, verbose_name='N.º de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='10 dígitos, empieza con 0 (ej. 0991234567).', max_length=10, validators=[reservas.validadores_ecuador.validar_telefono_ecuador]),
        ),
        migrations.AlterField(
            model_name='configuracionhotel',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, validators=[reservas.validadores_ecuador.validar_ruc], verbose_name='RUC'),
        ),
    ]
