# Generated by Django 5.1.5 on 2026-08-27 20:54

import reservas.validadores_ecuador
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_alter_cliente_cedula_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionhotel',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, validators=[reservas.validadores_ecuador.validar_telefono_ecuador]),
        ),
    ]
