# Generated by Django 5.1.5 on 2026-08-27 21:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_alter_configuracionhotel_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionhotel',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de IVA aplicado a la factura. Poné 0 si no corresponde cobrarlo.', max_digits=5, verbose_name='IVA (%)'),
        ),
    ]
