# Generated by Django 5.1.5 on 2026-08-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_configuracionhotel_iva_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='iva_monto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
