# Generated by Django 5.1.5 on 2026-08-27 21:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_factura_iva_monto_factura_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionhotel',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Los precios de las habitaciones ya incluyen IVA — este % solo se usa para desglosarlo en la factura. Poné 0 si no corresponde cobrarlo.', max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio por noche que paga el huésped, IVA incluido (sección 31). Si se deja en blanco se usa el del tipo.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Precio de referencia por noche, IVA incluido (sección 31).', max_digits=10),
        ),
    ]
