# Generated by Django 5.1.5 on 2026-08-28 00:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_alter_configuracionhotel_iva_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "Navidad", "Feriado de Carnaval".', max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('porcentaje_ajuste', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Negativo = descuento (ej. -20 para 20% off). Positivo = recargo de temporada alta. 0 = sin efecto en el precio.', max_digits=5, verbose_name='% de ajuste')),
                ('tema', models.CharField(choices=[('ninguno', 'Sin tema visual (solo precio)'), ('navidad', 'Navidad'), ('fin_de_ano', 'Fin de año'), ('san_valentin', 'San Valentín'), ('halloween', 'Halloween'), ('aniversario', 'Aniversario del hotel'), ('verano', 'Temporada de playa / verano')], default='ninguno', help_text='Si elegís uno distinto de "ninguno", el sistema cambia de colores mientras la fecha esté vigente.', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Desactivala para dejarla de aplicar sin borrarla.')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'fecha especial',
                'verbose_name_plural': 'fechas especiales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
